jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./users;MODE=PostgreSQL
    username: postgres
    password: none
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo
      username: mongodb
      password: mongodb
  main:
    allow-circular-references: true
server:
  port: 8080
